"""Pure Charter rules engine package."""

from .approvals import (
    COERCIVE_AUTHORITY_THRESHOLD,
    NON_COERCIVE_AUTHORITY_THRESHOLD,
    approval_passes_threshold,
    authority_formation_threshold,
    evaluate_approval_record,
)
from .records import (
    ApprovalRecord,
    AuthorityCharterRecord,
    AuthorityLifecycleState,
    AuthorityRecord,
    DelegationRecord,
    DelegationStatus,
    EventStatus,
    MetricRecord,
    RecordValidationError,
    RepresentativeRecord,
    RuleDecision,
    ScopeRecord,
    SimulationEvent,
    SubscriberRecord,
    ThresholdResult,
)
from .config import (
    CharterDerivativeConfig,
    ConfigLoadError,
    ScenarioConfig,
    load_charter_derivative,
    load_scenario,
    load_structured_file,
    validate_charter_derivative,
    validate_scenario,
)
from .events import (
    AUTHORITY_FORMATION_RULE_ID,
    DELEGATION_ACTIVATE_RULE_ID,
    DELEGATION_CREATE_RULE_ID,
    DELEGATION_REVOKE_RULE_ID,
    EVENT_PRIORITY,
    KNOWN_EVENT_TYPES,
    NO_OP_RULE_ID,
    EventInput,
    EventProcessor,
    TickProcessingResult,
)
from .lifecycle import (
    ALLOWED_AUTHORITY_TRANSITIONS,
    LifecycleTransitionError,
    can_execute_ordinary_action,
    can_transition_authority,
    transition_authority,
)
from .metrics import (
    ACTIVE_COUNTED_AUTHORITY_STATES,
    authority_count,
    delegation_churn,
    lifecycle_transition_count,
    raw_power_concentration,
)
from .outputs import (
    OUTPUT_FILENAMES,
    OutputArtifactPaths,
    RunOutputContext,
    write_run_outputs,
)
from .runner import ScenarioRunResult, run_scenario_config, run_scenario_file
from .rules import RuleMetadata, validate_rule_metadata
from .state import SimulationState, StateValidationError
from .validation import (
    ValidationFailedError,
    ValidationIssue,
    ValidationReport,
    ValidationSeverity,
)

__all__ = [
    "ApprovalRecord",
    "ACTIVE_COUNTED_AUTHORITY_STATES",
    "ALLOWED_AUTHORITY_TRANSITIONS",
    "AUTHORITY_FORMATION_RULE_ID",
    "AuthorityCharterRecord",
    "AuthorityLifecycleState",
    "AuthorityRecord",
    "CharterDerivativeConfig",
    "COERCIVE_AUTHORITY_THRESHOLD",
    "ConfigLoadError",
    "DELEGATION_ACTIVATE_RULE_ID",
    "DELEGATION_CREATE_RULE_ID",
    "DELEGATION_REVOKE_RULE_ID",
    "DelegationRecord",
    "DelegationStatus",
    "EVENT_PRIORITY",
    "EventInput",
    "EventProcessor",
    "EventStatus",
    "KNOWN_EVENT_TYPES",
    "LifecycleTransitionError",
    "MetricRecord",
    "NO_OP_RULE_ID",
    "NON_COERCIVE_AUTHORITY_THRESHOLD",
    "OUTPUT_FILENAMES",
    "OutputArtifactPaths",
    "RecordValidationError",
    "RepresentativeRecord",
    "RuleDecision",
    "RuleMetadata",
    "RunOutputContext",
    "ScopeRecord",
    "ScenarioConfig",
    "ScenarioRunResult",
    "SimulationEvent",
    "SimulationState",
    "StateValidationError",
    "SubscriberRecord",
    "ThresholdResult",
    "TickProcessingResult",
    "ValidationFailedError",
    "ValidationIssue",
    "ValidationReport",
    "ValidationSeverity",
    "approval_passes_threshold",
    "authority_count",
    "authority_formation_threshold",
    "can_execute_ordinary_action",
    "can_transition_authority",
    "delegation_churn",
    "evaluate_approval_record",
    "lifecycle_transition_count",
    "load_charter_derivative",
    "load_scenario",
    "load_structured_file",
    "raw_power_concentration",
    "run_scenario_config",
    "run_scenario_file",
    "transition_authority",
    "validate_charter_derivative",
    "validate_rule_metadata",
    "validate_scenario",
    "write_run_outputs",
]
